name: Sync to Notion

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository.
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          #cache: 'pip'
          #cache-dependency-path: setup.py

      - name: Install dependencies
        run: pip install git+https://github.com/apoorvkh/paperpile-to-notion.git@build

      - name: Run sync script
        run: python -m paperpile_to_notion
        env:
          NOTION_TOKEN: ${{secrets.NOTION_TOKEN}}
          DATABASE_IDENTIFIER: ${{secrets.DATABASE_IDENTIFIER}}
